# Generated by Django 4.2.1 on 2023-06-08 12:26

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_role', models.AutoField(db_column='id_Role', primary_key=True, serialize=False)),
                ('role_name', models.CharField(db_column='Role_Name', max_length=15, unique=True)),
                ('role_activity', models.BooleanField(db_column='Role_Activity')),
            ],
            options={
                'db_table': 'role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(db_column='id_User', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=15, verbose_name='Имя')),
                ('lastname', models.CharField(db_column='LastName', max_length=15, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, db_column='Patronomic', max_length=15, null=True, verbose_name='Отчество')),
                ('login', models.CharField(db_column='Login', help_text='Здесь вводится логин.', max_length=25, unique=True, verbose_name='Логин')),
                ('password', models.CharField(db_column='Password', max_length=25, verbose_name='Пароль')),
                ('number', models.CharField(blank=True, db_column='Number', max_length=15, null=True)),
                ('mail', models.EmailField(db_column='Mail', help_text='Здесь вводится почта.', max_length=25)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('is_staff', models.BooleanField(db_column='is_staff', default=False)),
                ('is_superuser', models.BooleanField(db_column='is_superuser', default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('role_id', models.ForeignKey(db_column='Role_id', default=4, on_delete=django.db.models.deletion.SET_DEFAULT, to='users.role')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'user',
            },
            managers=[
                ('objects', users.models.CustomUserManager()),
            ],
        ),
    ]
