# Generated by Django 4.2.1 on 2023-06-08 12:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(db_column='Password', max_length=25, validators=[django.core.validators.MaxLengthValidator(25)], verbose_name='Пароль'),
        ),
    ]
