# Generated by Django 4.2.1 on 2023-05-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('id_bus', models.AutoField(db_column='id_Bus', primary_key=True, serialize=False)),
                ('places', models.IntegerField(db_column='Places')),
                ('state_number', models.CharField(db_column='State_Number', max_length=10, unique=True)),
                ('image', models.ImageField(blank=True, db_column='Image', null=True, upload_to='tickets/')),
                ('description', models.TextField(blank=True, db_column='Description', max_length=250, null=True)),
                ('bus_activity', models.BooleanField(db_column='Bus_Activity')),
            ],
            options={
                'db_table': 'buses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BusMark',
            fields=[
                ('id_bus_mark', models.AutoField(db_column='id_Bus_Mark', primary_key=True, serialize=False)),
                ('name_bus_mark', models.CharField(db_column='Name_Bus_Mark', max_length=25, unique=True)),
                ('bus_mark_activity', models.BooleanField(db_column='Bus_Mark_Activity')),
            ],
            options={
                'db_table': 'bus_mark',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BusModels',
            fields=[
                ('id_bus_models', models.AutoField(db_column='id_Bus_Models', primary_key=True, serialize=False)),
                ('name_bus_models', models.CharField(db_column='Name_Bus_Models', max_length=30)),
                ('bus_models_activity', models.BooleanField(db_column='Bus_Models_Activity')),
            ],
            options={
                'db_table': 'bus_models',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BusStations',
            fields=[
                ('id_bus_stations', models.AutoField(db_column='id_Bus_Stations', primary_key=True, serialize=False)),
                ('adress', models.CharField(db_column='Adress', max_length=100)),
                ('bus_stations_activity', models.BooleanField(db_column='Bus_Stations_Activity')),
            ],
            options={
                'db_table': 'bus_stations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id_direction', models.AutoField(db_column='id_Direction', primary_key=True, serialize=False)),
                ('cost_route', models.DecimalField(db_column='Cost_Route', decimal_places=2, max_digits=7)),
                ('direction_activity', models.BooleanField(db_column='Direction_Activity')),
            ],
            options={
                'db_table': 'direction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id_ticket_type', models.AutoField(db_column='id_Ticket_Type', primary_key=True, serialize=False)),
                ('type_name', models.CharField(db_column='Type_Name', max_length=15, unique=True)),
                ('discount', models.DecimalField(db_column='Discount', decimal_places=2, max_digits=3)),
                ('ticket_type_activity', models.BooleanField(db_column='Ticket_Type_Activity')),
            ],
            options={
                'db_table': 'ticket_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id_timesheet', models.AutoField(db_column='id_Timesheet', primary_key=True, serialize=False)),
                ('date_time_departure', models.DateTimeField(db_column='Date_Time_Departure')),
                ('date_time_arrival', models.DateTimeField(db_column='Date_Time_Arrival')),
                ('timesheet_activity', models.BooleanField(db_column='Timesheet_Activity')),
            ],
            options={
                'db_table': 'timesheet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id_town', models.AutoField(db_column='id_Town', primary_key=True, serialize=False)),
                ('town_name', models.CharField(db_column='Town_Name', max_length=25, unique=True)),
                ('town_activity', models.BooleanField(db_column='Town_Activity')),
            ],
            options={
                'db_table': 'town',
                'managed': False,
            },
        ),
    ]
