# Generated by Django 4.2.1 on 2023-05-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id_order', models.AutoField(db_column='id_Order', primary_key=True, serialize=False)),
                ('data_order', models.DateTimeField(db_column='Data_Order')),
                ('number_tickets', models.IntegerField(db_column='Number_Tickets')),
                ('cost_total', models.DecimalField(db_column='Cost_Total', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
    ]
